// <auto-generated />
using System;
using FodApi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace FodApi.Data.Migrations
{
    [DbContext(typeof(FodContext))]
    [Migration("20200317014934_m1")]
    partial class m1
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("FodApi.Model.Candidat", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasMaxLength(40)
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("Candidatureid")
                        .HasColumnType("int");

                    b.Property<string>("date_de_naissance")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("experience")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("nom")
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("photo")
                        .IsRequired()
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("prenom")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("id");

                    b.HasIndex("Candidatureid");

                    b.ToTable("Candidat");
                });

            modelBuilder.Entity("FodApi.Model.Candidature", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasMaxLength(40)
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("cv")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("datepostulation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("status")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("type")
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("id");

                    b.ToTable("Candidature");
                });

            modelBuilder.Entity("FodApi.Model.Competence", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasMaxLength(40)
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("Candidatureid")
                        .HasColumnType("int");

                    b.Property<string>("libele")
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("id");

                    b.HasIndex("Candidatureid");

                    b.ToTable("Competence");
                });

            modelBuilder.Entity("FodApi.Model.Role", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasMaxLength(40)
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("Utilisateurid")
                        .HasColumnType("int");

                    b.Property<string>("designation")
                        .IsRequired()
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("id");

                    b.HasIndex("Utilisateurid");

                    b.ToTable("Role");
                });

            modelBuilder.Entity("FodApi.Model.Utilisateur", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasMaxLength(40)
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("email")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("mdp")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("nom")
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("photo")
                        .IsRequired()
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("prenom")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("id");

                    b.ToTable("Utilisateur");
                });

            modelBuilder.Entity("FodApi.Model.Candidat", b =>
                {
                    b.HasOne("FodApi.Model.Candidature", null)
                        .WithMany("candidat")
                        .HasForeignKey("Candidatureid");
                });

            modelBuilder.Entity("FodApi.Model.Competence", b =>
                {
                    b.HasOne("FodApi.Model.Candidature", null)
                        .WithMany("competence")
                        .HasForeignKey("Candidatureid");
                });

            modelBuilder.Entity("FodApi.Model.Role", b =>
                {
                    b.HasOne("FodApi.Model.Utilisateur", null)
                        .WithMany("role")
                        .HasForeignKey("Utilisateurid");
                });
#pragma warning restore 612, 618
        }
    }
}
