// <auto-generated />
using BackEnd.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace BackEnd.Migrations
{
    [DbContext(typeof(dbContext))]
    [Migration("20200401121251_TestModifier2.3")]
    partial class TestModifier23
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("BackEnd.Models.Candidat", b =>
                {
                    b.Property<int>("CandidatId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CandidatNom")
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("CandidatPrenom")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("DateDeNaissance")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Experience")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Photo")
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("CandidatId");

                    b.ToTable("Candidat");
                });

            modelBuilder.Entity("BackEnd.Models.Candidature", b =>
                {
                    b.Property<int>("CandidatureID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CV")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CandidatID")
                        .HasColumnType("int");

                    b.Property<string>("DatePostulation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Reponse")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CandidatureID");

                    b.HasIndex("CandidatID");

                    b.ToTable("Candidature");
                });

            modelBuilder.Entity("BackEnd.Models.Categorie", b =>
                {
                    b.Property<int>("CategorieID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Libelle")
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("CategorieID");

                    b.ToTable("Categorie");
                });

            modelBuilder.Entity("BackEnd.Models.Competence", b =>
                {
                    b.Property<int>("CompetenceID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CompetenceName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CompetenceID");

                    b.ToTable("Competence");
                });

            modelBuilder.Entity("BackEnd.Models.CompetenceCandidature", b =>
                {
                    b.Property<int>("CompetenceCandidatureID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CandidatureID")
                        .HasColumnType("int");

                    b.Property<int>("CompetenceID")
                        .HasColumnType("int");

                    b.HasKey("CompetenceCandidatureID");

                    b.HasIndex("CandidatureID");

                    b.HasIndex("CompetenceID");

                    b.ToTable("CompetenceCandidaure");
                });

            modelBuilder.Entity("BackEnd.Models.Question", b =>
                {
                    b.Property<int>("QuestionID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CategorieID")
                        .HasColumnType("int");

                    b.Property<string>("Ennonce")
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Rep1")
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Rep2")
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Rep3")
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("RepTrue")
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("QuestionID");

                    b.HasIndex("CategorieID");

                    b.ToTable("Question");
                });

            modelBuilder.Entity("BackEnd.Models.Test", b =>
                {
                    b.Property<int>("TestId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Date")
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Heure")
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("NbCandidature")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("NbPlace")
                        .HasColumnType("int");

                    b.Property<string>("Type")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TestId");

                    b.ToTable("Test");
                });

            modelBuilder.Entity("BackEnd.Models.TestCandidature", b =>
                {
                    b.Property<int>("TestCandidatureID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CandidatureID")
                        .HasColumnType("int");

                    b.Property<string>("Score")
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("TestID")
                        .HasColumnType("int");

                    b.HasKey("TestCandidatureID");

                    b.HasIndex("CandidatureID");

                    b.HasIndex("TestID");

                    b.ToTable("TestCandidature");
                });

            modelBuilder.Entity("BackEnd.Models.TestCategorie", b =>
                {
                    b.Property<int>("TestCategorieID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CategorieID")
                        .HasColumnType("int");

                    b.Property<int>("NbQuestion")
                        .HasColumnType("int");

                    b.Property<int>("TestID")
                        .HasColumnType("int");

                    b.HasKey("TestCategorieID");

                    b.HasIndex("CategorieID");

                    b.HasIndex("TestID");

                    b.ToTable("TestCategorie");
                });

            modelBuilder.Entity("BackEnd.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nom")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Prenom")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Token")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId");

                    b.ToTable("User");
                });

            modelBuilder.Entity("BackEnd.Models.Candidature", b =>
                {
                    b.HasOne("BackEnd.Models.Candidat", "Candidat")
                        .WithMany()
                        .HasForeignKey("CandidatID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BackEnd.Models.CompetenceCandidature", b =>
                {
                    b.HasOne("BackEnd.Models.Candidature", "Candidature")
                        .WithMany("CompetenceCandidature")
                        .HasForeignKey("CandidatureID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BackEnd.Models.Competence", "Competence")
                        .WithMany()
                        .HasForeignKey("CompetenceID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BackEnd.Models.Question", b =>
                {
                    b.HasOne("BackEnd.Models.Categorie", "Categorie")
                        .WithMany()
                        .HasForeignKey("CategorieID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BackEnd.Models.TestCandidature", b =>
                {
                    b.HasOne("BackEnd.Models.Candidature", "Candidature")
                        .WithMany()
                        .HasForeignKey("CandidatureID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BackEnd.Models.Test", "Test")
                        .WithMany("TestCandidature")
                        .HasForeignKey("TestID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BackEnd.Models.TestCategorie", b =>
                {
                    b.HasOne("BackEnd.Models.Categorie", "Categorie")
                        .WithMany()
                        .HasForeignKey("CategorieID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BackEnd.Models.Test", "Test")
                        .WithMany("TestCategorie")
                        .HasForeignKey("TestID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
